# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.

filter:
    paths: [dwlstng.php, inc/*, tpl/*]